In [34]:
pip install tensorflow

In [35]:
import tensorflow as tf
print(tf.__version__)

2.19.0


scalar

In [36]:
a = tf.constant(5)
b = tf.constant(10)

c = tf.add(a, b)
print(c)

d = tf.subtract(a, b)
print(d)

e = tf.multiply(a, b)
print(e)

f = tf.divide(a, b)
print(f)

g = tf.math.floordiv(a, b)
print(g)

p = tf.pow(b, 2)
print(p)

tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(-5, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(100, shape=(), dtype=int32)


1D vector

In [37]:
v = tf.constant([1,2,3,4])
u= tf.constant([5,6,7,8])
print(v)
print(u)

print("Add :",tf.add(v,u))
print("subtract : ",tf.subtract(v,u))
print("multiply : ",tf.multiply(v,u))
print("divide : ",tf.divide(v,u))
print("floordiv : ",tf.math.floordiv(v,u))
print("power : ",tf.pow(v,u))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
Add : tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
subtract :  tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
multiply :  tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
divide :  tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)
floordiv :  tf.Tensor([0 0 0 0], shape=(4,), dtype=int32)
power :  tf.Tensor([    1    64  2187 65536], shape=(4,), dtype=int32)


2D

In [38]:
m = tf.constant([[1, 2],
[3, 4]])
n = tf.constant([[5, 6],
[7, 8]])
print(m)
print(n)

print("Add :",tf.add(m,n))
print("subtract : ",tf.subtract(m,n))
print("multiply : ",tf.multiply(m,n))
print("divide : ",tf.divide(m,n))
print("floordiv : ",tf.math.floordiv(m,n))
print("power : ",tf.pow(m,n))


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
Add : tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
subtract :  tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
multiply :  tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
divide :  tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)
floordiv :  tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
power :  tf.Tensor(
[[    1    64]
 [ 2187 65536]], shape=(2, 2), dtype=int32)


3D

In [39]:
t3 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
